apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.37.0
    helm:
      releaseName: cluster-autoscaler
      values: |
        autoDiscovery:
          clusterName: my-eks-cluster
        
        awsRegion: us-east-1  
        
        rbac:
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/ClusterAutoscalerRole
        
        extraArgs:
          scale-down-enabled: true
          scale-down-delay-after-add: 5m           
          scale-down-unneeded-time: 5m            
          scale-down-utilization-threshold: 0.65   
          skip-nodes-with-system-pods: false
          balance-similar-node-groups: true
          max-node-provision-time: 15m
          scale-down-delay-after-delete: 0s       
          
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true