apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Jtwoolbright/terraform-eks-argocd-platform-2.0
    targetRevision: main
    path: application/k8-manifests/nginx
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true